This commit was manufactured by cvs2svn to create tag 'v2-1'.

diff --git a/alien-installer b/alien-installer
--- a/alien-installer
+++ b/alien-installer
@@ -5,15 +5,6 @@
 #
 # modification history
 # $Log$
-# Revision 1.62  2005/08/02 13:53:17  buncic
-# Allow installer updates to new version (-r vN-M)
-#
-# Revision 1.61  2005/07/18 10:51:45  buncic
-# Streamlining alien-installer, removing a few questions...
-#
-# Revision 1.60  2005/07/07 07:39:36  buncic
-# Fixed download URL (/download and not /dist)
-#
 # Revision 1.59  2005/07/06 21:00:15  buncic
 # Changed release label in installer
 #
@@ -190,13 +181,14 @@
 # CREATION DATE:
 #C<
 #############################################################################
-VERSION=0.03
+VERSION=0.02
 ###########################################################################
 [ -f $HOME/.alien/installer.rc ] && . $HOME/.alien/installer.rc
 ###########################################################################
-ALIEN_INSTALLER_HOME=${ALIEN_INSTALLER_HOME:=$HOME/.alien/cache}
+ALIEN_INSTALLER_HOME=${ALIEN_INSTALLER_HOME:=$HOME/alien}
 ALIEN_INSTALLER_URL=${ALIEN_INSTALLER_URL:=rsync://alien.cern.ch:8873/releases} 
 ALIEN_INSTALLER_CVS=${ALIEN_INSTALLER_CVS:=":pserver:cvs@alisoft.cern.ch:/soft/cvsroot"}
+ALIEN_INSTALLER_BINARY_UPDATE=${ALIEN_INSTALLER_BINARY_UPDATE:=0}
 ALIEN_INSTALLER_PREFIX=${ALIEN_INSTALLER_PREFIX:=/opt/alien}
 ALIEN_INSTALLER_METHOD=${ALIEN_INSTALLER_METHOD:=bininstall}
 ALIEN_INSTALLER_AUTODETECT=${ALIEN_INSTALLER_AUTODETECT:=false}
@@ -204,8 +196,6 @@ ALIEN_INSTALLER_TYPE=${ALIEN_INSTALLER_TYPE:=all}
 ALIEN_INSTALLER_PLATFORM=${ALIEN_INSTALLER_PLATFORM:=}
 ALIEN_DIALOG=${ALIEN_DIALOG:=dialog}
 ALIEN_RELEASE=${ALIEN_RELEASE:=HEAD}
-ALIEN_BITS_URL=${ALIEN_BITS_URL:=http://alienbuild.cern.ch:8888/$ALIEN_INSTALLER_PLATFORM/$ALIEN_RELEASE/download/} 
-ALIEN_INSTALLER_TYPE=$(echo $ALIEN_INSTALLER_TYPE | sed 's/+/ /g')
 ECHO=""
 ###########################################################################
 InstallerRcUpdate()
@@ -213,10 +203,10 @@ InstallerRcUpdate()
 {
   mkdir -p $HOME/.alien
   (
-    ALIEN_INSTALLER_TYPE=$(echo $ALIEN_INSTALLER_TYPE | sed 's/ /+/g')
     echo "ALIEN_INSTALLER_HOME=$ALIEN_INSTALLER_HOME" 
     echo "ALIEN_INSTALLER_URL=$ALIEN_INSTALLER_URL" 
     echo "ALIEN_INSTALLER_CVS=$ALIEN_INSTALLER_CVS" 
+    echo "ALIEN_INSTALLER_BINARY_UPDATE=$ALIEN_INSTALLER_BINARY_UPDATE" 
     echo "ALIEN_INSTALLER_PREFIX=$ALIEN_INSTALLER_PREFIX" 
     echo "ALIEN_INSTALLER_METHOD=$ALIEN_INSTALLER_METHOD" 
     echo "ALIEN_INSTALLER_AUTODETECT=$ALIEN_INSTALLER_AUTODETECT" 
@@ -224,7 +214,6 @@ InstallerRcUpdate()
     echo "ALIEN_INSTALLER_PLATFORM=$ALIEN_INSTALLER_PLATFORM" 
     echo "ALIEN_DIALOG=$ALIEN_DIALOG" 
     echo "ALIEN_RELEASE=$ALIEN_RELEASE" 
-    echo "ALIEN_BITS_URL=$ALIEN_BITS_URL" 
   ) > $HOME/.alien/installer.rc
 
 }
@@ -244,7 +233,6 @@ Error()
 {
    dialog $style --msgbox "$1" $height $width 
    [ $debug -eq 0 ] &&  clear
-   [ -f install.log ] && cat install.log  
    exit 1
 }
 ###########################################################################
@@ -266,7 +254,7 @@ InstallerMake()
         then
           Error "No such package: $dir"
         fi
-        $ECHO make -C $dir $cmd >> install.log 2>&1 || Exit 1
+        $ECHO make -C $dir $cmd > install.log 2>&1 || Exit 1
       done
     done
   fi
@@ -284,7 +272,7 @@ InstallerMakePkg()
     then
       Error "No such package: $dir"
     fi
-    $ECHO make -C $dir $cmd >> install.log 2>&1 || Exit 1
+    $ECHO make -C $dir $cmd > install.log 2>&1 || Exit 1
   done
 }
 
@@ -481,9 +469,6 @@ InstallerUpdate()
     rm -rf apps/*/*/cookies/*binextract* apps/*/*/cookies/*relocate*
   fi
 
-  ALIEN_BITS_URL="http://alienbuild.cern.ch:8888/$ALIEN_INSTALLER_PLATFORM/$ALIEN_RELEASE/download/"
-
- (cd $ALIEN_INSTALLER_HOME; ./alien-installer -p $ALIEN_INSTALLER_HOME -r $ALIEN_RELEASE configure --with-alien-release=$ALIEN_RELEASE  --with-platform=$ALIEN_INSTALLER_PLATFORM --with-bits-url=$ALIEN_BITS_URL --prefix=$ALIEN_INSTALLER_PREFIX > install.log 2>&1 ) 
 
   for meta in $ALIEN_INSTALLER_TYPE
   do
@@ -511,9 +496,11 @@ InstallerUpdate()
   then
     echo 'Running post installation scripts...'
     $ALIEN_INSTALLER_PREFIX/bin/alien-perl --bootstrap --prefix $ALIEN_INSTALLER_PREFIX
-    $ALIEN_INSTALLER_PREFIX/bin/alien configure >> install.log
+  else
+    echo 'Installation failed: alien-perl not found.' 
   fi
 
+  $ALIEN_INSTALLER_PREFIX/bin/alien configure >> install.log
 }
 
 
@@ -527,7 +514,7 @@ InstallerUI()
 
   export TPUT=undef
 
-  style="--title AliEn-Installer-v$VERSION --clear"
+  style="--title AliEn-Installer-v0.01 --clear"
 
   release_file=`mktemp /tmp/release.XXXXXX`
   cache_file=`mktemp /tmp/cache.XXXXXX`
@@ -549,7 +536,22 @@ InstallerUI()
 
   cmd=$cmd" --with-alien-release=$ALIEN_RELEASE "
 
-  ALIEN_INSTALLER_METHOD='bininstall'
+  $ALIEN_DIALOG  $style \
+          --radiolist "PLEASE SELECT THE INSTALLATION METHOD"  0 0 0 \
+                      "Binary" "Download precompiled packages"   on  \
+                      "Source" "Compile everything from sources" 0 2>$dialog_file  || Exit 1
+
+  method=`cat $dialog_file`
+
+  if [ "$method" == "Source" ]
+  then
+    ALIEN_INSTALLER_METHOD='reinstall'
+    ALIEN_INSTALLER_BINARY_UPDATE=0
+  else
+    cmd=$cmd" -b "
+    ALIEN_INSTALLER_METHOD='bininstall'
+    ALIEN_INSTALLER_BINARY_UPDATE=1
+  fi
 
   $ALIEN_DIALOG  $style --defaultno \
           --yesno "Would you like installer to autodetect and reuse already installed software components on your system?" 0 0 
@@ -591,16 +593,18 @@ InstallerUI()
 
   platform=$ALIEN_INSTALLER_PLATFORM
 
-  if [ "$ALIEN_INSTALLER_PLATFORM" == "" ]
-  then 
+  if [ "$method" == "Binary" ]
+  then
+    if [ "$ALIEN_INSTALLER_PLATFORM" == "" ]
+    then 
       platform=$($workspace/platform.sh platform)
-  fi
+    fi
 
-  $ALIEN_DIALOG  $style \
+    $ALIEN_DIALOG  $style \
             --yesno "Detected/configured platform setting for this machine is $platform. Press YES if you want to keep it that way or press NO if you want to select another supported platform." 0 0
 
-  if [ $? -eq 1 ] 
-  then 
+    if [ $? -eq 1 ] 
+    then 
        $ALIEN_DIALOG $style \
                   --radiolist 'PLEASE SELECT PLATFORM:' 0 0 0 \
                               'i686-pc-linux-gnu'         'Linux i686' on \
@@ -609,17 +613,22 @@ InstallerUI()
                               'powerpc-apple-darwin8.1.0' 'MacOS X'    0  2>$dialog_file || Exit 1 
       prefix=`cat $dialog_file`
       cmd=$cmd"--with-platform=$platform "
+    fi
   fi
 
   ALIEN_INSTALLER_PLATFORM=$platform  
 
-  caches=`grep -v -e "^#" $cache_file | grep $platform | awk -v platform=$ALIEN_INSTALLER_PLATFORM -v release=$ALIEN_RELEASE -F'|' '{printf("%s/%s/%s/download/",$2,platform,release)}' | sed 's/ *//'`
-  cmd=$cmd" --with-bits-url=$caches "
-
-  ALIEN_BITS_URL=$caches
-
-  $ALIEN_DIALOG  $style --sleep 3 \
-          --infobox "Using $caches repository..."
+  if [ "$method" == "Binary" ]
+  then
+     caches=`grep -v -e "^#" $cache_file | grep $platform | awk -v platform=$ALIEN_INSTALLER_PLATFORM -v release=$ALIEN_RELEASE -F'|' '{printf("%s/%s/%s/download/",$2,platform,release)}' | sed 's/ *//'`
+     cmd=$cmd" --with-bits-url=$caches "
+     $ALIEN_DIALOG  $style \
+          --yesno "Installer will use the following binary caches to download AliEn components: $caches. Do you want to continue?" 0 0 
+     if [ $? -eq 1 ] 
+     then
+        Exit 1 
+     fi
+  fi
 
   prefix=$ALIEN_INSTALLER_PREFIX
 
@@ -629,7 +638,7 @@ InstallerUI()
   fi
 
   $ALIEN_DIALOG $style \
-         --yesno "Default installation location location is $prefix. Press YES if you want to keep it that way or press NO if you want to select another location." $height $width
+         --yesno "Default installation location location is $prefix. Press YES if you want to keep it that way or press NO if you want to select another location. Please note that the installation directory must be different form workspace directory." $height $width
 
   if [ $? -eq 1 ]
   then
@@ -783,10 +792,19 @@ do
 	    ALIEN_INSTALLER_PLATFORM=$1
             shift 1
            ;;
+        --method)
+            shift 1
+	    ALIEN_INSTALLER_METHOD=$1
+            shift 1
+           ;;
         --prefix)
             shift 1
 	    ALIEN_INSTALLER_PREFIX=$1
             shift 1
+           ;;
+        -b|--binary|--binary-update)
+            shift 1
+	    ALIEN_INSTALLER_BINARY_UPDATE=1
            ;;
         -a|--autodetect)
             shift 1
@@ -842,7 +860,14 @@ do
            ;;
         install)
            shift 1
-           InstallerMake bininstall $*
+           case $ALIEN_INSTALLER_BINARY_UPDATE in
+             1|true|TRUE|True|yes|Yes|YES|Y)
+               InstallerMake bininstall $*
+               ;;
+             *)
+               InstallerMake install $*
+               ;;
+           esac
            exit
            ;;
         configure)
@@ -891,6 +916,7 @@ Common commmands:
   index      - force rebuild of package cache 
 
 Options:
+  -b, --binary       - use binary packages 
   -p, --build-prefix - installation directory
   -u, --url          - cache url         
   -h, --help         - display this help text
@@ -907,8 +933,10 @@ Installer options:
   --release <RELEASE>        [HEAD] 
   --type <installation type> [all,client,portal,site,core,wn]
   --platform <platform>      [,i686-pc-linux-gnu,ia64-unknown-linux-gnu,powerpc-apple-darwin7.7.0]
+  --method <method>          [bininstall,install]  
   --prefix <path>            [/opt/alien]  
   --home <path>              [$HOME/alien]
+  --binary-update   
   --autodetect
  
 Configure options:
